# Generated by Django 3.0.1 on 2019-12-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Manager', 'Manager'), ('Finance Manager', 'Finance Manager')], default='Regular', max_length=20),
        ),
    ]
