# Generated by Django 3.0.1 on 2019-12-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='submitted_date',
        ),
        migrations.AlterField(
            model_name='tour',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
