# Generated by Django 3.0.1 on 2019-12-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
