# Generated by Django 3.0.1 on 2019-12-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20191220_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Submitted to Finance', 'Submitted to Finance'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Request for Information', 'Request for Information')], default='Draft', max_length=25),
        ),
    ]
